### PR TITLE
Websocket fix

### LINKED ISSUE #145: Tag deletion on tag page is buggy
To recreate: add two or three new tags to a restaurant. Go to the tag page and delete one of the new tags. It will appear as though multiple tags have been deleted.

Then, go back to the main page. Adding a new tag or restaurant results in duplicates being created.

### PR DESCRIPTION
**Pull request by nyscherm**
Close websocket when leaving home page to avoid situations where multiple websockets are open. Fixes #145.

### CODE REVIEW

**Comment by nyscherm** [comment]
Fixes #145

File: src/reducerMaps/tags.js [hunk 1]
```diff
@@ -85,15 +85,23 @@ export default new Map([
   ],
   [ActionTypes.DELETE_TAG, isFetching],
   [ActionTypes.TAG_DELETED, (state, action) =>
-    update(state, {
+  {
+    const tagIndex = getTagIds({ tags: state }).indexOf(action.id);
+    let items = {};
+    if (tagIndex !== -1) {
+      items = {
```
Comment (JeffreyATW) [inline src/reducerMaps/tags.js]: instead of `let items = {}`, move `newState` up and make this line `newState.items = {`

File: src/reducerMaps/tags.js [hunk 2]
```diff
@@ -85,23 +85,22 @@ export default new Map([
...
-        result: {
-          $splice: [[tagIndex, 1]]
+    {
+      const tagIndex = getTagIds({ tags: state }).indexOf(action.id);
+      const newState = {
+        isFetching: {
+          $set: false
         }
       };
+      newState.items = {};
```
Comment (JeffreyATW) [inline src/reducerMaps/tags.js]: No need for this line
